### PR TITLE
#165305221 Users should be able to Signup

### PR DESCRIPTION
**Pull request by ElishaMisoi**
### What does this PR do?

Users should be able to Signup and or Register using Sign up forms on the signup route.

### Description of the task to be completed?

- Ensure an email is sent to a user once they sign up in order to activate their account
- Register user
- Activate user account

### How should you manually test this?

- [x] **Clone the repository**

        $ git clone https://github.com/andela/ah-the-jedi-frontend.git

- [x] **Switch to testing branch**

       $ git checkout ft-signup-register-165305221

- [x] **Switch to the ah-the-jedi-frontend directory**

       $ cd ah-the-jedi-frontend/

 

- [x] **Install project dependencies**

       $ npm install

### Running the application

      $ npm start

- [x] **Signup a user**

### Screenshots
          
Screenshot 2019-05-31 at 10 55 55

- [x] **Go to the registered email inbox and click verification link**
Screenshot 2019-05-31 at 10 56 46

- [x] **Account Activated**
###Screenshots
Screenshot 2019-05-31 at 11 20 50

### What are the relevant PT stories?

[#165305221](https://www.pivotaltracker.com/story/show/165305221)

### CODE REVIEW

**Review by jkamz — COMMENTED** [review]
Very nice implementation @Elisha-Misoi . However, I feel like you should disable the signup button until all frontend validations are done. Thanks.

**Comment by ElishaMisoi** [comment]
> Very nice implementation @Elisha-Misoi . However, I feel like you should disable the signup button until all frontend validations are done. Thanks.

@jkamz this won't be a good implementation in a Sign Up form as opposed to Sign In form because the user must be informed as to why the button is disabled. The input fields are quite a lot as compared to the Sign Up form hence it's more efficient to show validation messages such as 'password character length' once the user has clicked the submit button.

**Review by AlvinMugambi — APPROVED** [review]

**Review by katherine95 — APPROVED** [review]
LGTM. Great work implementing sign up

**Review by Benkimeric — COMMENTED** [review]
Nice work on implementing user signup. Great work on styling the Navigation bar

**Pull request merged**
